<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Helpdesk.Assets.Domain</RootNamespace>
    <AssemblyName>Asset.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Helpdesk.Contracts\Helpdesk.Contracts.csproj" />
  </ItemGroup>
</Project>
