<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Helpdesk.Clients.Domain</RootNamespace>
    <AssemblyName>Client.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Helpdesk.Contracts\Helpdesk.Contracts.csproj" />
  </ItemGroup>
</Project>
